import { ApplicationType, DashboardDataType, InternshipType, RecentApplicantType } from '@/types';

export const dummyInternships: InternshipType[] = [
  {
    id: 1,
    status: 'open',
    title: 'Web dev intern',
    department: 'Ministry of IT',
    description:
      "This is a web development internship focused on building modern web applications using React and Node.js. You'll work on government digital services and citizen portals.",
    location: 'New Delhi',
    duration: '3 months',
    stipend: '$12000/month',
    applicationDeadline: new Date('2025-09-17'),
    startDate: new Date('2025-10-01'),
    requiredSkills: ['React.js', 'Next.js', 'Node.js'],
    preferredSkills: ['TypeScript', 'MongoDB', 'Git'],
    applications: 2,
  },
  {
    id: 2,
    status: 'open',
    title: 'Frontend Developer Intern',
    department: 'Digital India Initiative',
    description:
      'Work on user interface development for government digital services and citizen portals using modern React ecosystem.',
    location: 'Mumbai',
    duration: '6 months',
    stipend: '$15000/month',
    applicationDeadline: new Date('2025-10-15'),
    startDate: new Date('2025-11-01'),
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'JavaScript'],
    preferredSkills: ['Next.js', 'Redux', 'Framer Motion'],
    applications: 12,
  },
  {
    id: 3,
    status: 'open',
    title: 'Backend Developer Intern',
    department: 'Ministry of Technology',
    description:
      'Develop robust APIs and database systems for large-scale government applications. Work with microservices architecture.',
    location: 'Bangalore',
    duration: '4 months',
    stipend: '$14000/month',
    applicationDeadline: new Date('2025-09-30'),
    startDate: new Date('2025-10-15'),
    requiredSkills: ['Node.js', 'Express.js', 'MongoDB', 'PostgreSQL'],
    preferredSkills: ['Docker', 'AWS', 'Redis', 'GraphQL'],
    applications: 8,
  },
  {
    id: 4,
    status: 'closed',
    title: 'Data Science Intern',
    department: 'Ministry of Statistics',
    description:
      'Analyze government data sets and create machine learning models for policy insights and predictive analytics.',
    location: 'Remote',
    duration: '5 months',
    stipend: '$16000/month',
    applicationDeadline: new Date('2025-08-30'),
    startDate: new Date('2025-09-15'),
    requiredSkills: ['Python', 'TensorFlow', 'SQL', 'Pandas'],
    preferredSkills: ['PyTorch', 'Jupyter', 'R', 'Tableau'],
    applications: 25,
  },
  {
    id: 5,
    status: 'open',
    title: 'Mobile App Developer',
    department: 'Ministry of Health',
    description:
      'Build mobile applications for healthcare services and patient management systems using React Native and Flutter.',
    location: 'Chennai',
    duration: '4 months',
    stipend: '$13000/month',
    applicationDeadline: new Date('2025-11-20'),
    startDate: new Date('2025-12-01'),
    requiredSkills: ['React Native', 'Flutter', 'JavaScript', 'Redux'],
    preferredSkills: ['Expo', 'Firebase', 'SQLite', 'Push Notifications'],
    applications: 6,
  },
  {
    id: 6,
    status: 'open',
    title: 'DevOps Engineer Intern',
    department: 'Ministry of Defense',
    description:
      'Manage cloud infrastructure and deployment pipelines for secure government systems. Work with containerization and orchestration.',
    location: 'Hyderabad',
    duration: '6 months',
    stipend: '$17000/month',
    applicationDeadline: new Date('2025-10-05'),
    startDate: new Date('2025-10-20'),
    requiredSkills: ['AWS', 'Docker', 'Kubernetes', 'Jenkins'],
    preferredSkills: ['Terraform', 'Ansible', 'Prometheus', 'Grafana'],
    applications: 4,
  },
  {
    id: 7,
    status: 'open',
    title: 'UI/UX Design Intern',
    department: 'Ministry of Education',
    description:
      'Design intuitive user experiences for educational platforms and learning management systems. Create wireframes and prototypes.',
    location: 'Pune',
    duration: '3 months',
    stipend: '$11000/month',
    applicationDeadline: new Date('2025-09-25'),
    startDate: new Date('2025-10-10'),
    requiredSkills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    preferredSkills: ['Sketch', 'InVision', 'Principle', 'Adobe Creative Suite'],
    applications: 18,
  },
  {
    id: 8,
    status: 'open',
    title: 'Cybersecurity Intern',
    department: 'Ministry of Electronics',
    description:
      'Work on security assessments and vulnerability testing for government digital infrastructure. Learn ethical hacking techniques.',
    location: 'Delhi',
    duration: '5 months',
    stipend: '$18000/month',
    applicationDeadline: new Date('2025-11-10'),
    startDate: new Date('2025-11-25'),
    requiredSkills: ['Ethical Hacking', 'Network Security', 'Python', 'Linux'],
    preferredSkills: ['Kali Linux', 'Metasploit', 'Wireshark', 'OWASP'],
    applications: 9,
  },
];

export const dummyApplications: ApplicationType[] = [
  {
    id: 1,
    internshipId: 1,
    position: 'Web dev intern',
    fullName: 'Krish Bansal',
    email: 'krish.bansal@email.com',
    phone: '+91 98765 43210',
    graduationDate: new Date('2025-06-15'),
    university: 'Maharaja surajmal institute',
    degree: 'bca',
    gpa: 8.5,
    coverLetter:
      'I am writing to express my strong interest in the Web Development Intern position. With my background in computer applications and experience with modern web technologies, I believe I would be a valuable addition to your team.',
    status: 'rejected',
    appliedAt: new Date('2025-09-11T14:00:00Z'),
  },
  {
    id: 2,
    internshipId: 1,
    position: 'Web dev intern',
    fullName: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+91 87654 32109',
    graduationDate: new Date('2025-05-20'),
    university: 'IIT Delhi',
    degree: 'computer science engineering',
    gpa: 9.2,
    coverLetter:
      'Dear Hiring Manager, I am excited to apply for the Web Development Intern position. My strong academic background combined with hands-on experience in React and Node.js makes me an ideal candidate for this role.',
    status: 'accepted',
    appliedAt: new Date('2025-09-12T08:00:00Z'),
  },
  {
    id: 3,
    internshipId: 2,
    position: 'Frontend Developer Intern',
    fullName: 'Amit Sharma',
    email: 'amit.sharma@email.com',
    phone: '+91 76543 21098',
    graduationDate: new Date('2025-07-10'),
    university: 'Delhi University',
    degree: 'btech computer science',
    gpa: 7.8,
    coverLetter:
      'Hello, I would like to apply for the Frontend Developer Intern position. I have good knowledge of React and JavaScript.',
    status: 'pending',
    appliedAt: new Date('2025-09-12T11:00:00Z'),
  },
  {
    id: 4,
    internshipId: 1,
    position: 'Web dev intern',
    fullName: 'Priya Patel',
    email: 'priya.patel@email.com',
    phone: '+91 65432 10987',
    graduationDate: new Date('2025-06-30'),
    university: 'Mumbai University',
    degree: 'information technology',
    gpa: 8.9,
    coverLetter:
      'I am writing to apply for the Web Development Intern position. My academic excellence and passion for web technologies make me a strong candidate for this opportunity.',
    status: 'under review',
    appliedAt: new Date('2025-09-11T16:30:00Z'),
  },
];

export const dummyDashboardData: DashboardDataType = {
  stats: [
    { title: 'Total Applications', value: '127', type: 'total' },
    { title: 'Open Positions', value: '8', type: 'open' },
    { title: 'Under Review', value: '23', type: 'review' },
    { title: 'Accepted', value: '45', type: 'accepted' },
    { title: 'Avg AI Score', value: '78/100', type: 'score' },
  ],

  statusDistribution: [
    { status: 'pending', count: 34 },
    { status: 'under review', count: 23 },
    { status: 'accepted', count: 45 },
    { status: 'rejected', count: 10 },
  ],

  sentimentAnalysis: [
    { sentiment: 'Positive', count: 67 },
    { sentiment: 'Neutral', count: 42 },
    { sentiment: 'Negative', count: 18 },
  ],
};

export const recentApplicantsDummyData: RecentApplicantType[] = [
  {
    id: 1,
    fullName: 'Krish Bansal',
    university: 'Maharaja surajmal institute',
    degree: 'bca',
    status: 'rejected',
    aiScore: 60,
  },
  {
    id: 2,
    fullName: 'Sarah Johnson',
    university: 'IIT Delhi',
    degree: 'computer science engineering',
    status: 'accepted',
    aiScore: 92,
  },
  {
    id: 3,
    fullName: 'Amit Sharma',
    university: 'Delhi University',
    degree: 'btech computer science',
    status: 'pending',
    aiScore: 75,
  },
  {
    id: 4,
    fullName: 'Priya Patel',
    university: 'Mumbai University',
    degree: 'information technology',
    status: 'under review',
    aiScore: 84,
  },
  {
    id: 5,
    fullName: 'Rahul Kumar',
    university: 'NIT Kurukshetra',
    degree: 'software engineering',
    status: 'pending',
    aiScore: 78,
  },
  {
    id: 6,
    fullName: 'Ananya Singh',
    university: 'Bits Pilani',
    degree: 'computer science',
    status: 'accepted',
    aiScore: 89,
  },
  {
    id: 7,
    fullName: 'Vikash Gupta',
    university: 'Jamia Millia Islamia',
    degree: 'mca',
    status: 'rejected',
    aiScore: 55,
  },
  {
    id: 8,
    fullName: 'Neha Verma',
    university: 'DU North Campus',
    degree: 'computer applications',
    status: 'under review',
    aiScore: 81,
  },
];
